cloud: anyscale_v2_default_cloud
head_node:
  instance_type: m5.4xlarge
  resources:
    CPU: 0
    GPU: 0
  flags: {}
worker_nodes:
  - instance_type: m5.4xlarge
    flags: {}
    min_nodes: 0
    max_nodes: 2
    market_type: ON_DEMAND
  - instance_type: m5.4xlarge
    resources:
      CPU: 16
      GPU: 1
    flags: {}
    min_nodes: 0
    max_nodes: 2
    market_type: ON_DEMAND
enable_cross_zone_scaling: false
advanced_instance_config:
  TagSpecifications:
    - Tags:
        - Key: buildkite_job_id
          Value: 019e2a0a-05b7-44a9-8239-eb0e7afc5c51
        - Key: buildkite_pull_request
          Value: 'false'
        - Key: buildkite_organization_slug
          Value: ray-project
        - Key: buildkite_pipeline_slug
          Value: release
        - Key: buildkite_build_id
          Value: 019e2a04-a2fa-4a9f-b8ea-d5ff63a0c544
        - Key: buildkite_build_number
          Value: '92911'
        - Key: buildkite_source
          Value: trigger_job
        - Key: release_frequency
          Value: nightly
        - Key: test_name
          Value: pg_autoscaling_regression_test.aws
        - Key: test_smoke_test
          Value: 'False'
        - Key: release_test_team
          Value: core
        - Key: release_test_env
          Value: ''
      ResourceType: instance
    - Tags:
        - Key: buildkite_job_id
          Value: 019e2a0a-05b7-44a9-8239-eb0e7afc5c51
        - Key: buildkite_pull_request
          Value: 'false'
        - Key: buildkite_organization_slug
          Value: ray-project
        - Key: buildkite_pipeline_slug
          Value: release
        - Key: buildkite_build_id
          Value: 019e2a04-a2fa-4a9f-b8ea-d5ff63a0c544
        - Key: buildkite_build_number
          Value: '92911'
        - Key: buildkite_source
          Value: trigger_job
        - Key: release_frequency
          Value: nightly
        - Key: test_name
          Value: pg_autoscaling_regression_test.aws
        - Key: test_smoke_test
          Value: 'False'
        - Key: release_test_team
          Value: core
        - Key: release_test_env
          Value: ''
      ResourceType: volume
  BlockDeviceMappings:
    - Ebs:
        VolumeSize: 500
        DeleteOnTermination: true
      DeviceName: /dev/sda1
auto_select_worker_config: false
idle_termination_minutes: 120
flags:
  allow-cross-zone-autoscaling: false
